### ISSUE TITLE
`LD_PRELOAD` execution causes segfault

### ISSUE THREAD

**Issue by Bojun-Seo** [honggyukim/heaptrace#18]
`heaptrace` can be run without `heaptrace` binary file.
Following two commands are interchangeable.
```
$ ./heaptrace samples/sample.out
$ LD_PRELOAD=./libheaptrace.so samples/sample.out
```
But the latter generates segfault.
```
$ LD_PRELOAD=./libheaptrace.so samples/sample.out
Segmentation fault (core dumped)
```

**Comment by honggyukim** [comment]
The problem was because `getenv` returns `NULL` when using `LD_PRELOAD` directly so it gets crashed. This is fixed by 89823f9 so please read the commit message.
