### ISSUE TITLE
Report in `size` order as well as `count` order at the same time

### ISSUE THREAD

**Issue by Bojun-Seo** [honggyukim/heaptrace#9]
Current `heaptrace` need to decide the report order. `size` or `count`.
I want to check the report order in `size` and `count` in some cases.
So it would be nice if it is possible to report in `size` order as well as `count` order at the same time.

**Comment by honggyukim** [comment]
@Bojun-Seo I have pushed the changes to [multiple_sort_keys](https://github.com/honggyukim/heaptrace/compare/main...multiple_sort_keys).

The change allows `-s`/`--sort` option have multiple sort keys. For example, `-s count,size` is a valid argument and it shows the stacktrace based on `count` and `size` together. The stacktrace shows following the given order.

Please have a look at the change and let me know if this is what you need.

**Comment by Bojun-Seo** [comment]
@honggyukim it looks great!
And you could add an issue to support flame graph for `multiple sort keys`

**Comment by honggyukim** [comment]
The usage of `--flame-graph` is that user redirects the output into a file so if the output prints multiple output then it can't be directly converted into `.png` by `flamegraph.pl` script so I don't want to do that. Do you really need it for `--flame-graph` as well?

**Comment by Bojun-Seo** [comment]
In fact, I don't use `flame graph` feature, so I don't need it.
But I guess it could be possible to make two pair of outputs and each of one could be converted into `.png` by `flamegraph.pl`.
It seems pretty hard to make pair of outputs, since `--flame-graph` option only print the output into `outfp` which could be `stdout` or user given output file.
So we need to decide some sort of policies to make two pair of outputs.
And that's why I'd like to generate issue and discuss further(and later).

**Comment by honggyukim** [comment]
OK. I got it. We will need another interface to support multiple sort orders for flamegraph. But I’m okay to create an issue and think about it later. I will merge the current change only then.

**Comment by honggyukim** [comment]
> And you could add an issue to support flame graph for multiple sort keys

@Bojun-Seo Please see #12.
